web/router.ex
defmodule Sportsgeist.Router do
  use Sportsgeist.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    #plug Sportsgeist.Locale
  end

  # This plug will look for a Guardian token in the session in the default location
  # Then it will attempt to load the resource found in the JWT.
  # If it doesn't find a JWT in the default location it doesn't do anything
  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Sportsgeist do
    pipe_through [:browser, :browser_auth]  # Use the default browser stack

    get "/", PageController, :index
    delete "/logout", AuthController, :logout

    resources "/tokens", TokenController
    resources "/users", UserController
    post "/users/:id/password", UserController, :change_password
    post "/users/:id/profile", UserController, :change_profile
    resources "/courses", CourseController
  end

  # This scope is the main authentication area for Ueberauth
  scope "/auth", Sportsgeist do
    pipe_through [:browser, :browser_auth] # Use the default browser stack

    get "/:identity", AuthController, :login
    get "/:identity/callback", AuthController, :callback
    post "/:identity/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", Sportsgeist do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Sportsgeist.LayoutView do
  use Sportsgeist.Web, :view

  @doc """
  Returns "active" if the currently request path is equal to the path definition
  expected (from the menu entry) given by path
  """
  def is_active(conn, expected_path) do
    if Regex.regex?(expected_path) do
      if String.match?(conn.request_path,expected_path) do
        "active"
      else
        ""
      end
    else
      if conn.request_path == expected_path do
        "active"
      else
        ""
      end
    end
  end

  def course_image() do
    :rand.seed(:exsplus)
    ["pexels-photo-60230.jpeg","pexels-photo-87835.jpeg","sport-fitness-workout-resolution.jpg"]
    |> Enum.random
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sportsgeist</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>" >
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link "-:||----||:- Sportsgeist", to: page_path(@conn, :index), class: "navbar-brand"%>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <%= if @current_user do %>
                  <li class="<%= is_active(@conn, page_path(@conn, :index))%>"><%= link gettext("Home"), to: page_path(@conn, :index)%></li>
                  <li class="<%= is_active(@conn, ~r(#{course_path(@conn, :index)}) )%>"><%= link gettext("Courses"), to: course_path(@conn, :index) %></li>
                <% end %>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <%= if @current_user do %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= @current_user.nickname %> <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><%= link gettext("Profile"), to: user_path(@conn, :show, @current_user.id) %></li>
                      <!-- li role="separator" class="divider"></li -->
                    </ul>
                  </li>
                  <li><%= button "Logout", to: auth_path(@conn, :logout), method: :delete, class: "btn btn-default navbar-btn" %></li>
                <% else %>
                  <li>
                    <%= if @conn.request_path != auth_path(@conn, :login, "identity") do %>
                      <%= button "Login", to: auth_path(@conn, :login, "identity"), method: "get", class: "btn btn-primary navbar-btn"%>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
      </header>

      <div class="container-fluid">
        <%= if get_flash(@conn, :info) do %>
          <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <% end %>
        <%= if get_flash(@conn, :error) do %>
          <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        <% end %>

        <main role="main">
          <%= render @view_module, @view_template, assigns %>
        </main>
      </div>

      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2016, 2017 Michael Engelhardt.
          &middot; <a href="#">Privacy</a>
          &middot; <a href="#">Terms</a>
          &middot; <a href="https://bitbucket.org/0x0me/sportsgeist" target="_blank"><span class="label label-default"><i class="fa fa-bitbucket-square" aria-hidden="true"></i> Bitbucket</span>
</a>
        </p>
      </footer>
    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>require("web/static/js/app").App.run()</script>
  </body>
</html>

web/templates/layout/frontpage.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sportsgeist</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>" >
  </head>

  <body>
        <div class="navbar-wrapper">
          <div class="container">
            <header class="header">
              <nav class="navbar navbar-default">
                <div class="container-fluid">
                  <!-- Brand and toggle get grouped for better mobile display -->
                  <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
                    <%= link "-:||----||:- Sportsgeist", to: page_path(@conn, :index), class: "navbar-brand"%>
                  </div>

                  <!-- Collect the nav links, forms, and other content for toggling -->
                  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                      <%= if @current_user do %>
                        <li class="<%= is_active(@conn, page_path(@conn, :index))%>"><%= link gettext("Home"), to: page_path(@conn, :index)%></li>
                        <li class="<%= is_active(@conn, ~r(#{course_path(@conn, :index)}) )%>"><%= link gettext("Courses"), to: course_path(@conn, :index) %></li>
                      <% end %>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                      <%= if @current_user do %>
                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= @current_user.nickname %> <span class="caret"></span></a>
                          <ul class="dropdown-menu">
                            <li><%= link gettext("Profile"), to: user_path(@conn, :show, @current_user.id) %></li>
                            <!-- li role="separator" class="divider"></li -->
                          </ul>
                        </li>
                        <li><%= button "Logout", to: auth_path(@conn, :logout), method: :delete, class: "btn btn-default navbar-btn" %></li>
                      <% else %>
                        <li>
                          <%= if @conn.request_path != auth_path(@conn, :login, "identity") do %>
                            <%= button "Login", to: auth_path(@conn, :login, "identity"), method: "get", class: "btn btn-primary navbar-btn"%>
                          <% end %>
                        </li>
                      <% end %>
                    </ul>
                  </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
              </nav>
            </header>

          </div>
        </div>


        <!-- Carousel
        ================================================== -->
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <img class="first-slide" src="/images/pexels-photo-60230.jpeg" alt="First slide">
              <div class="container">
                <div class="carousel-caption" style="color: black;">
                  <h1>Starte einen neuen Sportkurs.</h1>
                  <p>Erstelle einfach Deinen Sportkurs und lade Deine Freunde dazu ein.</p>
                  <%= if ! @current_user do %>
                  <p><a class="btn btn-lg btn-primary" href="<%= user_path(@conn, :new) %>" role="button">Erstelle eine Konto</a></p>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="item">
              <img class="second-slide" src="/images/pexels-photo-87835.jpeg" alt="Second slide">
              <div class="container">
                <div class="carousel-caption">
                  <h1>Verabrede Dich mit Deinen Freunden zum Training.</h1>
                  <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                  <%= if ! @current_user do %>
                    <p><a class="btn btn-lg btn-primary" href="<%= user_path(@conn, :new) %>" role="button">Erstelle eine Konto</a></p>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="item">
              <img class="third-slide" src="/images/sport-fitness-workout-resolution.jpg" alt="Third slide">
              <div class="container">
                <div class="carousel-caption">
                  <h1>Trainiere mit Deinen Freunden zusammen.</h1>
                  <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                  <%= if ! @current_user do %>
                    <p><a class="btn btn-lg btn-primary" href="<%= user_path(@conn, :new) %>" role="button">Erstelle eine Konto</a></p>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div><!-- /.carousel -->

      <div class="container-fluid">
        <main role="main">
          <%= render @view_module, @view_template, assigns %>
        </main>
      </div>

      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2016, 2017 Michael Engelhardt.
          &middot; <a href="#">Privacy</a>
          &middot; <a href="#">Terms</a>
          &middot; <a href="https://bitbucket.org/0x0me/sportsgeist" target="_blank"><span class="label label-default"><i class="fa fa-bitbucket-square" aria-hidden="true"></i> Bitbucket</span>
</a>
        </p>
      </footer>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>require("web/static/js/app").App.run()</script>
  </body>
</html>